### ISSUE TITLE
todo secondary

### ISSUE THREAD

**Issue by marvinmai** [marvinmai/E-Smog-Meter#1]
### Implementierung einer grafischen Übersicht

- [ ] Erstellen eines neuen Fragments, Titel: "Grafisch"
- [ ] Erstellen eines Senso-Listeners, benötigt wird der Betrag
- [ ] Implementierung eines Graphen, in dem die Daten des Senors in Echtzeit dargestellt werden
  - [ ] In Echtzeit: In einem festgelegten Intervall (optional einstellbar) wird die Ansicht aktualisiert
  - [ ] Bei aktualisierung wird nicht ein neuer Datenpunkt eingetragen, sondern die bis dahin angefallenen eingetragen; dadurch gleichbleibende Auflösung und keine ungenauere Anzeige bei geringerem Intervall
